### ISSUE TITLE
doas asks for password

### ISSUE THREAD

**Issue by TonyBostonTB** [vedetta-com/caesonia#118]
Hi,

at OpenPGP Web Key Service (WKS)
```
doas -u vmail \
	env -i HOME=/var/vmail \
	gpg-wks-server --list-domains
```
doas asks for a password, although it shouldn't
Any ideas?

**Comment by horia** [comment]
It should ask for password, and can be temporarily disabled in [doas.conf](https://github.com/vedetta-com/caesonia/blob/master/src/etc/doas.conf)
```
# WKS: expire non confirmed publication requests
permit nopass root as vmail cmd env #args \
#    -i HOME=/var/vmail /usr/local/bin/gpg-wks-server --cron
```

**Comment by TonyBostonTB** [comment]
ahh I see, but you didn't mention to set a password for user vmail ;)
