### ISSUE TITLE
caesonia openbsd vm?

### ISSUE THREAD

**Issue by mhekeler** [vedetta-com/caesonia#144]
Hello,

is it possible to install caesonia in vmd(8)?
Are there any special options to respect when setup the vm so that all is running fine?

**Comment by horia** [comment]
It is possible to run in vmd(8), @gonzalo- uses this [setup](http://cvs.x61.com.ar/cgi-bin/cvsweb/vmm_setup) with [-current](http://cvs.x61.com.ar/cgi-bin/cvsweb/ansible-role-mailserver/)
I haven't tried it yet, but it's on my to-do. If you give it a try, please update this issue with any problems.

p.s.
- there's a new Virtualization FAQ https://www.openbsd.org/faq/faq16.html
- https://OpenBSD.amsterdam allows email service on their vmd(8)

**Comment by mhekeler** [comment]
> (...)
>     * https://OpenBSD.amsterdam allows email service on their vmd(8)

Yes I see - but I can't run my own `vmd(8)` on their service.

**Comment by mhekeler** [comment]
Thank you both
