### ISSUE TITLE
missing line in smtpd.conf?

### ISSUE THREAD

**Issue by TonyBostonTB** [vedetta-com/caesonia#162]
I couldn't send messages as authenticated user unless I added the following line
`match auth from any for any action "relay"`

Is this missing in the config file or did I miss someting else?

edit: okay, so this mail then doesn't use dkimroxy, right? 

btw, the error I was getting was "invalid recipient" for ANY recipient I tried - seems dkimproxy somehow got borked. Ideas anyone?

**Comment by TonyBostonTB** [comment]
that was from IP. btw, I just updated from 6.3 to 6.4 two days ago. I guess I forgot something here

**Comment by horia** [comment]
To see what's going on, e.g matching rules:
https://man.openbsd.org/smtpd#T
> Enables real-time tracing at startup
`smtpd -dvT rules`

There is no missing line, to my knowledge. After auth, the message goes through dkimproxy_out on IPv4 `127.0.0.1` not IPv6 `::1` (dkimproxy needs a small patch to work with IPv6, not part of the OpenBSD package)

**Comment by horia** [comment]
[*] dkimproxy IPv6 patch https://svnweb.freebsd.org/ports/head/mail/dkimproxy/files/

**Comment by TonyBostonTB** [comment]
Do you know how to tell that `::1` should not be used?

**Comment by horia** [comment]
Please test again with this patch.

**Comment by TonyBostonTB** [comment]
thank you @horia 
Well, I could have seen this myself I guess - it's working again
