### ISSUE TITLE
Auto renew certs and OCSP responses?

### ISSUE THREAD

**Issue by Katzeilla** [vedetta-com/caesonia#231]
Seem like we have to renew certs and OCSP responses manually (Since acme-client doesn't renew automatically :( ), maybe I should write a script to do that every 3 months using Cron?

**Comment by horia** [comment]
https://man.openbsd.org/acme-client#EXAMPLES

I moved the acme-client(1) daily cron(8) job (to renew the certificate as necessary, and reload/restart services,) to daily(8) https://github.com/vedetta-com/caesonia/blob/master/src/etc/daily.local

https://man.openbsd.org/ocspcheck

Next, ocspcheck(8) saves the response from the OCSP server.

**Comment by Katzeilla** [comment]
Thanks for your explanation! :)
