### ISSUE TITLE
Any recent update for 6.6?

### ISSUE THREAD

**Issue by epsilon-0** [vedetta-com/caesonia#249]
I wanted to know if this was going to get updated for OpenBSD 6.6?

I am currently following poolp's guide and was checking if this one would be simpler.

I'm pretty interested in seeing how this goes.

Thanks a lot for making this!

**Comment by Katzeilla** [comment]
I don't think update is needed as I am running this with 6.6 now, and it works just fine. :)

**Comment by epsilon-0** [comment]
Indeed, I actually changed this up and managed to get my own configuration in https://github.com/AnsiMail/AnsiMail which extends this.

It was very informative and does look like most of this is going to keep working.
