### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by wesley974** [vedetta-com/caesonia#45]
Perhaps add a documentation about how things works, how to install ...

**Comment by h0r14** [comment]
Install Guide #50 
Some things could be scripted, suggestions welcomed.

**Comment by wesley974** [comment]
I will review this tomorrow, come back to you with feedback!

**Comment by wesley974** [comment]
**Review 1
syspatch # perhaps move to 'syspatch && reboot' ?

**Review 2 
Add git package

**Review 3
What's about the following tasks ? Do we need to do that ?

--- +dovecot-2.2.32p0 -------------------
Files to facilitate the generation of a self-signed
certificate and key for Dovecot have been installed:
/etc/ssl/dovecot-openssl.cnf (Edit this accordingly!)
/usr/local/sbin/dovecot-mkcert.sh

If this has been or will be accomplished by other means,
use the following paths for the files:
/etc/ssl/dovecotcert.pem
/etc/ssl/private/dovecot.pem
--- +python-2.7.14 -------------------
If you want to use this package as your default system python, as root
create symbolic links like so (overwriting any previous default):
 ln -sf /usr/local/bin/python2.7 /usr/local/bin/python
 ln -sf /usr/local/bin/python2.7-2to3 /usr/local/bin/2to3
 ln -sf /usr/local/bin/python2.7-config /usr/local/bin/python-config
 ln -sf /usr/local/bin/pydoc2.7  /usr/local/bin/pydoc

**Review 4
Explain the 2 users : vmail and dsync
Role ?

**Review 5
Instead of using ftp to get the src files, why not just use 'git clone' ?
cd && git clone https://github.com/vedetta-com/caesonia
cd caesonia/src/

**Review 6
Typo : Virtua domain name # need to be 'Virtual'

**Review 7
Typo : find . -t`ype f -exec sed -i 's|example.net|example.org|g' {} + # need to be '-type'

**Review 8
sed -e -i "s|puffy|$USER|g" src/etc/pf.conf \
src/etc/mail/aliases \
src/etc/ssh/sshd_config
==>sed: 1: "-i": invalid command code -

**Review 9
Update virtual users and domains:
src/etc/mail/passwd # explain the syntax
src/etc/mail/virtual # explain how it works (add|update|delete user, domain, alias)

**Review 10
Typo : install -o root -g wheel -m 0644 -b src/etc/dovecot/conf.d/* /tmp/dovecot/conf.d/ # need to be /etc instead of /tmp

**Review 11
# sievec /var/dovecot/imapsieve/before/spamtest.sieve
error: script not found.
sievec(wesley): Fatal: failed to compile sieve script '/var/dovecot/imapsieve/before/spamtest.sieve'

**Review 12
rcctl start httpd => give me with debug mode (-d) the following error
/etc/httpd.conf:51: failed to load public/private keys for server r62.aise.local

Stop here for the moment.

**Comment by h0r14** [comment]
> syspatch # perhaps move to 'syspatch && reboot' ?

`syspatch -c` runs on first boot, when I would instinctively patch and `reboot` again if necessary.
e.g. `reboot` > [`syspatch`] [`reboot`] > `mail`

The rest of the changes hopefully fix the other review points, thank you.

**Comment by wesley974** [comment]
I will try asap from a new fresh OpenBSD 6.2 amd64 installed. Thank's for your changes!

**Comment by h0r14** [comment]
Merging INSTALL.md to master.
Please open a new Issue or Pull Request if needed.
Thanks again @wesley974
